/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Target = (props) => {
  const group = useRef();
  const { nodes, materials } = useGLTF("src/assets/target.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Cylinder015.geometry}
          material={materials["Red.024"]}
        />
        <mesh
          geometry={nodes.Cylinder015_1.geometry}
          material={materials["White.024"]}
        />
      </group>
    </group>
  );
};

useGLTF.preload("src/assets/target.gltf");

export default Target;
